version: '3'
services:
  core:
    container_name: core
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      PHP_XDEBUG_REMOTE_PORT: "${PHP_XDEBUG_REMOTE_PORT}"
      PHP_XDEBUG_REMOTE_HOST: "${PHP_XDEBUG_REMOTE_HOST}"
    volumes:
      - ${CORE_PATH}:/app
    ports:
      - "5000:8080"
    depends_on:
      - database
  web:
    container_name: web
    build:
      context: ./
      dockerfile: ./node-conf/Dockerfile
    volumes:
      - ${WEB_PATH}:/app
    ports:
      - "5001:8080"
  database:
    container_name: database
    image: "postgres:13.3"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      - POSTGRES_DB=resserv
      - POSTGRES_USER=${DATABASE_USER_NAME}
      - POSTGRES_PASSWORD=${DATABASE_USER_PASSWORD}
