version: '3'
services:
  core:
    container_name: core
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      PHP_XDEBUG_REMOTE_PORT: "${PHP_XDEBUG_REMOTE_PORT}"
      PHP_XDEBUG_REMOTE_HOST: "${PHP_XDEBUG_REMOTE_HOST}"
    volumes:
      - ${CORE_PATH}:/app
    ports:
      - "5000:8080"
  web:
    container_name: web
    build:
      context: ./
      dockerfile: ./node-conf/Dockerfile
    volumes:
      - ${WEB_PATH}:/app
    ports:
      - "5001:8080"
  mysql:
    container_name: mysql
    image: "mysql:8"
    expose:
      - "3306"
    ports:
      - "${DATABASE_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
